### PR TITLE
fix: missing ']' in substitution- ln122

### PR DESCRIPTION
**Pull request by aenichols**
image

image

image

Issue with path separators on windows. I suggest converting the filepath to '/' if you are on windows.

### CODE REVIEW

**Comment by gpanders** [comment]
Can you try the `windows` branch for me?

**Comment by aenichols** [comment]
I will give this a try tomorrow morning, thanks for the help.

**Comment by gpanders** [comment]
Did you ever get a chance to try that branch? If it resolves your issue, I’ll merge it.

**Comment by aenichols** [comment]
> Did you ever get a chance to try that branch? If it resolves your issue, I’ll merge it.

Sorry, it took me so long. I did just pull it down and everything seems to be working as expected. =]

**Pull request closed without merging**
